<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo ",,,,,,,,,,,,,,,,,Kimball Gunsmithing,,,2203 Condor St,,United States,USA,,,Colorado,CO,Colorado Springs,,,,80909,(719) 630-0966,,,,Dealer,9/12/2012,1/1/2014,active,Limited,Archery & Firearms->Dealers & Stores->Colorado,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Kimball Rod And Gun Club,kimballrodandgun@hotmail.com,,9837 Willow Creek Road,,United States,USA,,,Minnesota,MN,Kimball,,,,55353,,,,,Women'sYouth Programs || Shotgun || Rifle || InstructionRentals || Handgun || Archery,9/12/2012,1/1/2014,active,Limited,Archery & Firearms->Ranges->Minnesota,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,\"Kimball, Roger Keith\",,,707 Trenton St,,United States,USA,,,Louisiana,LA,West Monroe,,,,71291,(318) 396-1002,,,,Gun Stores || Gun Dealers || Stores,9/12/2012,1/1/2014,active,Limited,Archery & Firearms->Dealers & Stores->Louisiana,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Kimber Manufacturing,info@kimberamerica.com,http://www.kimberamerica.com,,,United States,USA,,,New York,NY,,,,,10705,(800) 880-2418,(406) 758-2223,,,,9/12/2012,1/1/2014,active,Limited,Archery & Firearms->Dealers & Stores->New York,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Kimber Mfg Inc,,,1 Lawton St,,United States,USA,,,New York,NY,Yonkers,,,,10705,(914) 964-0771,,,,Gun Stores || Gun Dealers || Stores,9/12/2012,1/1/2014,active,Limited,Archery & Firearms->Dealers & Stores->New York,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Kimber Mfg Inc,,,1 Lawton Street,,United States,USA,,,New York,NY,Yonkers,,,,10705,(914) 964-0771,,,,Gun Stores || Gun Dealers || Stores,9/12/2012,1/1/2014,active,Limited,Archery & Firearms->Dealers & Stores->New York,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Kimberkoch Inc,,,11830 Shotgun Way,,United States,USA,,,Texas,TX,Helotes,,,,78023,(210) 695-6407,,,,Gun Stores || Gun Dealers || Stores,9/12/2012,1/1/2014,active,Limited,Archery & Firearms->Dealers & Stores->Texas,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Kimberlin Firearms,,,7341 S 1100 E,,United States,USA,,,Indiana,IN,Scipio,,,,47273,(812) 579-5663,,,,Dealer,9/12/2012,1/1/2014,active,Limited,Archery & Firearms->Dealers & Stores->Indiana,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Kimberly Farms Hunting Club,,,31116 380Th St,,United States,USA,,,Minnesota,MN,Aitkin,,,,56431,(218) 549-3402,,,,Dealer,9/12/2012,1/1/2014,active,Limited,Archery & Firearms->Dealers & Stores->Minnesota,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Kimberly Gun Repair,,,3641 N - 3500 E,,United States,USA,,,Idaho,ID,Kimberly,,,,83341,(208) 423-4196,,,,Dealer,9/12/2012,1/1/2014,active,Limited,Archery & Firearms->Dealers & Stores->Idaho,,,,,\n";
?>
