<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,ListINg State AbbrevIAtion,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo ",,,,,,,,,,,,,,,,,Dixieland Aphc,appyspots@mchsi.com,www.dixielandaphc.com,1173 Boles Road,,,,,,Alabama,AL,New Market,,,,35761,(256)-828-0457,,,,Association || Clubs || Organizations,3/28/2012,5/1/2013,Active,Diamond,AL->Equine->Associations,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Heart Of Dixie Aphc,darlabmaher@gmail.com,www.heartofdixieaphc.com,21070 Broadwater Rd,,,,,,Alabama,AL,Athens,,,,35614,(256)-527-9490,,,,Association || Clubs || Organizations,3/28/2012,5/1/2013,Active,Diamond,AL->Equine->Associations,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Arizona Appaloosa Assn,fathorsefarm@hotmail.com,www.arizonaappaloosa.com,1812 East La Salla Rd,,,,,,Arizona,AZ,Phoenix,,,,85086,(623)-465-4948,,,,Association || Clubs || Organizations,3/28/2012,5/1/2013,Active,Diamond,AZ->Equine->Associations,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Southern Arizona Aphc,neumanda4h@aol.com,www.saappaloosa.org,9041 N Calle Loma Linda,,,,,,Arizona,AZ,Tucson,,,,85704,(520)-297-3153,,,,Association || Clubs || Organizations,3/28/2012,5/1/2013,Active,Diamond,AZ->Equine->Associations,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Arkansas Appaloosa Inc,rockw@earthlink.net,www.arkansasaphc.com,Po Box 242117,,,,,,Arkansas,AR,Little Rock,,,,72223,(870)-540-7690,,,,Association || Clubs || Organizations,3/28/2012,5/1/2013,Active,Diamond,AR->Equine->Associations,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Calizona Aphc,terriharthorses3@aol.com,www.czappaloosa.com,9590 Beekley Rd,,,,,,California,CA,Phelan,,,,92371,(760)-249-3533,,,,Association || Clubs || Organizations,3/28/2012,5/1/2013,Active,Diamond,CA->Equine->Associations,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,E Wa Tom Lih Kinh Aphc,ewaappaloosa@yahoo.com,,4141 Deer Creek Rd #65,,,,,,California,CA,Fremont,,,,94555,(510)-744-1876,,,,Association || Clubs || Organizations,3/28/2012,5/1/2013,Active,Diamond,CA->Equine->Associations,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Golden Empire Aphc,lobeliaflower@yahoo.com,www.goldenempireappaloosahorseclub.com,6900 Kimberly Ave,,,,,,California,CA,Bakersfield,,,,93308,(661)-392-1047,,,,Association || Clubs || Organizations,3/28/2012,5/1/2013,Active,Diamond,CA->Equine->Associations,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Mid Valley Aphc,hotrod.annie@earthlink.net,,806 W Harding Rd,,,,,,California,CA,Turlock,,,,95380,(209)-632-1252,,,,Association || Clubs || Organizations,3/28/2012,5/1/2013,Active,Diamond,CA->Equine->Associations,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Northern Cal Aphc,whiningwoman@frontiernet.net,,14610 Oak Run Rd,,,,,,California,CA,Oak Run,,,,96069,(530)-472-3453,,,,Association || Clubs || Organizations,3/28/2012,5/1/2013,Active,Diamond,CA->Equine->Associations,,,,,\n";
?>
