<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo ",,,,,,,,,,,,,,,,,Jaguar of the Gulf Coast,,http://www.joebullard.com,1151 E I65 Service Rd S,,United States,USA,,,Alabama,AL,Mobile,,,,36606,(866) 975-2115,,,,Truck Dealers,3/11/2012,5/1/2013,Active,Diamond,AL->Agriculture->Truck Dealers,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Superior Petroleum Services Inc.,,http://www.spsservice.com,201 Shell Rd,,United States,USA,,,Alabama,AL,Saraland,,,,36571,(800) 949-4660,,,,Farm Equipment,3/11/2012,5/1/2013,Active,Diamond,AL->Agriculture->Farm Equipment,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,2 B's Auto Sales,,http://2bsautosales.com,2100 Highway 412 E,,United States,USA,,,Arkansas,AR,Siloam Springs,,,,72761,(479) 524-9701,,,,Truck Dealers,3/11/2012,5/1/2013,Active,Diamond,AR->Agriculture->Truck Dealers,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Aaa Mini Storage,,http://aaaministorage1.com,1619 E Centerton Blvd,,United States,USA,,,Arkansas,AR,Bentonville,,,,72712,(479) 795-0754,,,,Trailers,3/11/2012,5/1/2013,Active,Diamond,AR->Agriculture->Trailers,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,ABC Equipment,,http://abcequip.com,6902 Brodie Ln,,United States,USA,,,Arkansas,AR,Little Rock,,,,72204,(501) 455-2457,,,,Hardware Stores,3/11/2012,5/1/2013,Active,Diamond,AR->Agriculture->Hardware Stores,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,ABC Block & Equipment,,http://abcequip.com,2485 N Shiloh Dr,,United States,USA,,,Arkansas,AR,Fayetteville,,,,72704,(479) 442-5746,,,,Hardware Stores,3/11/2012,5/1/2013,Active,Diamond,AR->Agriculture->Hardware Stores,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,American Building Specialties,,http://abspecialties.net,6717 Crystal Hill Rd,,United States,USA,,,Arkansas,AR,North Little Rock,,,,72118,(501) 791-2024,,,,Hardware Stores,3/11/2012,5/1/2013,Active,Diamond,AR->Agriculture->Hardware Stores,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Timmins Hardware Inc.,,http://acehardware.com,101 E 5th St,,United States,USA,,,Arkansas,AR,El Dorado,,,,71730,(870) 863-7104,,,,Hardware Stores,3/11/2012,5/1/2013,Active,Diamond,AR->Agriculture->Hardware Stores,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Ace Hardware Retail Support Center,,http://acehardware.com,400 Murphy Dr,,United States,USA,,,Arkansas,AR,Maumelle,,,,72113,(501) 851-4450,,,,Hardware Stores,3/11/2012,5/1/2013,Active,Diamond,AR->Agriculture->Hardware Stores,,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Fasco Hardware,,http://acehardware.com,801 S Division St,,United States,USA,,,Arkansas,AR,Blytheville,,,,72315,(870) 763-7766,,,,Hardware Stores,3/11/2012,5/1/2013,Active,Diamond,AR->Agriculture->Hardware Stores,,,,,\n";
?>
