<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Title,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo ",,,,,,,,,,,,,,,,,,Silks Restaurant,http://remingtonpark.com/dining/silks_restaurant,1 Remington Pl,,United States,USA,,,,OK,Oklahoma City,,,,73111,(405) 425-3280,,,,Oklahoma || Remmington Park || Restaurants || Food,,4/1/2013,active,,OK->TRAVEL->Restaurants,OK->Remmington Park->Restaurants,,,,\n";
	echo ",,,,,,,,,,,,,,,,,,Sonic Drive-In,http://www.sonicdrivein.com/,2801 NE 50th St,,United States,USA,,,,OK,Oklahoma City,,,,73111,(405) 424-5266,,,,Oklahoma || Remmington Park || Restaurants || Food,,4/1/2013,active,,OK->TRAVEL->Restaurants,OK->Remmington Park->Restaurants,,,,\n";
	echo ",,,,,,,,,,,,,,,,,,SUBWAY,http://www.subway.com/,5745 N Martin Luther King Ave,,United States,USA,,,,OK,Oklahoma City,,,,73111,(405) 604-9890,,,,Oklahoma || Remmington Park || Restaurants || Food,,4/1/2013,active,,OK->TRAVEL->Restaurants,OK->Remmington Park->Restaurants,,,,\n";
	echo ",,,,,,,,,,,,,,,,,,Pizza Factory,http://www.pizzafactoryinc.com,5745 N Martin Luther King Ave,,United States,USA,,,,OK,Oklahoma City,,,,73111,(405) 424-0736,,,,Oklahoma || Remmington Park || Restaurants || Food,,4/1/2013,active,,OK->TRAVEL->Restaurants,OK->Remmington Park->Restaurants,,,,\n";
	echo ",,,,,,,,,,,,,,,,,,McDonald's,http://www.mcdonalds.com,5815 N Martin Luther King Ave,,United States,USA,,,,OK,Oklahoma City,,,,73111,(405) 424-1141,,,,Oklahoma || Remmington Park || Restaurants || Food,,4/1/2013,active,,OK->TRAVEL->Restaurants,OK->Remmington Park->Restaurants,,,,\n";
	echo ",,,,,,,,,,,,,,,,,,Sonic Drive-In,http://www.sonicdrivein.com/,6101 N Martin Luther King Ave,,United States,USA,,,,OK,Oklahoma City,,,,73111,(405) 427-5700,,,,Oklahoma || Remmington Park || Restaurants || Food,,4/1/2013,active,,OK->TRAVEL->Restaurants,OK->Remmington Park->Restaurants,,,,\n";
	echo ",,,,,,,,,,,,,,,,,,Adairs Inc,http://henryhudsonspub.com,6205 N Bryant Ave,,United States,USA,,,,OK,Oklahoma City,,,,73121,(405) 478-2515,,,,Oklahoma || Remmington Park || Restaurants || Food,,4/1/2013,active,,OK->TRAVEL->Restaurants,OK->Remmington Park->Restaurants,,,,\n";
	echo ",,,,,,,,,,,,,,,,,,National Cowboy & Western Heritage Museum,http://www.nationalcowboymuseum.org,1700 NE 63rd St,,United States,USA,,,,OK,Oklahoma City,,,,73111,(405) 478-2250,,,,Oklahoma || Remmington Park || Restaurants || Food,,4/1/2013,active,,OK->TRAVEL->Restaurants,OK->Remmington Park->Restaurants,,,,\n";
	echo ",,,,,,,,,,,,,,,,,,Dining On Persimmon Hill,http://www.yellowpages.com/oklahoma-city-ok/mip/dining-on-persimmon-hill-451331599?lid=451331599,1700 NE 63rd St,,United States,USA,,,,OK,Oklahoma City,,,,73111,(405) 478-2250,,,,Oklahoma || Remmington Park || Restaurants || Food,,4/1/2013,active,,OK->TRAVEL->Restaurants,OK->Remmington Park->Restaurants,,,,\n";
	echo ",,,,,,,,,,,,,,,,,,Haunted House Restaurant,http://www.hauntedhouserestaurant.com,7101 Miramar Blvd,,United States,USA,,,,OK,Oklahoma City,,,,73111,(405) 478-1417,,,,Oklahoma || Remmington Park || Restaurants || Food,,4/1/2013,active,,OK->TRAVEL->Restaurants,OK->Remmington Park->Restaurants,,,,\n";
?>
