<?
	header("Content-Type: text/csv; charset=UTF-8", TRUE);

	echo "Account Username,Account Password,Account Contact First Name,Account Contact Last Name,Account Contact Company,Account Contact Address,Account Contact Address2,Account Contact Country,Account Contact State,Account Contact City,Account Contact Postal Code,Account Contact Phone,Account Contact Fax,Account Contact Email,Account Contact URL,Legacy ID,Listing ID,Listing Title,Listing Email,Listing URL,Listing Address,Listing Address2,Listing Country,Listing Country Abbreviation,Listing Region,Listing Region Abbreviation,Listing State,Listing State Abbreviation,Listing City,Listing City Abbreviation,Listing Neighborhood,Listing Neighborhood Abbreviation,Listing Postal Code,Listing Phone,Listing Fax,Listing Short Description,Listing Long Description,Listing Keywords,Updated Date,Listing Renewal Date,Listing Status,Listing Level,Listing Category 1,Listing Category 2,Listing Category 3,Listing Category 4,Listing Category 5,Listing Template\n";
	echo ",,,,,,,,,,,,,,,,,Radisson Suites Tucson,,http://www.radissontuscon.com,6555 E Speedway Blvd,,United States,USA,,,Arizona,AZ,Tucson,,,,85710,(202) 465-3959,,,,Hotels || Rillito Park (Pima Fair),3/10/2012,5/1/2013,Active,Diamond,AZ->Travel->Hotels,AZ->Travel->Rillito Park (Pima Fair)->Hotels,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Econo Lodge Oxmoor,,http://birmingham.citysearch.com/profile/external/1371368/orange_tx/econo_lodge_oxmoor.html?publisher=yellowpages&reference_id=1&placement=ypwebsitesrpo,2245 Highway 62 S,,United States,USA,,,Texas,TX,Orange,,,,77630,(205) 941-0990,,,,Hotels || Delta Downs,3/10/2012,5/1/2013,Active,Diamond,TX->Travel->Hotels,TX->Travel->Delta Downs->Hotels,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Gil's Towing,,,2062577384,,United States,USA,,,Washington,WA,Seattle,,,,98104,(206) 257-7384,,,,Towing Services || Sun Downs,3/10/2012,5/1/2013,Active,Diamond,WA->Travel->Towing Services,WA->Travel->Sun Downs->Towing Services,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Haute Coifs,,http://www.hautecoifs.com,9527 Westheimer Rd,,United States,USA,,,Texas,TX,Houston,,,,77063,(206) 271-1606,,,,Salons || Houston Race Park,3/10/2012,5/1/2013,Active,Diamond,TX->Travel->Salons,TX->Travel->Houston Race Park->Salons,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Chara Joyner at Wrapped in Wellness,,http://www.hautecoifs.com,5000 Westheimer Rd,,United States,USA,,,Texas,TX,Houston,,,,77056,(206) 271-1606,,,,Salons || Houston Race Park,3/10/2012,5/1/2013,Active,Diamond,TX->Travel->Salons,TX->Travel->Houston Race Park->Salons,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Apollo Spas,,http://apollospas.com/,,,United States,USA,,,Washington,WA,,,,,,(206) 575-2700,,,,Spas || Dayton,3/10/2012,5/1/2013,Active,Diamond,WA->Travel->Spas,WA->Travel->Dayton->Spas,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Hot Yoga for Life,,http://www.hotyogaforlife.com,714 North Fremont Street,,United States,USA,,,Oregon,OR,Portland,,,,97227,(206) 992-9031,,,,Gyms || Portland Meadows,3/10/2012,5/1/2013,Active,Diamond,OR->Travel->Gyms,OR->Travel->Portland Meadows->Gyms,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Teton Valley Towing,,,,,United States,USA,,,Idaho,ID,,,,,,(208) 201-5950,,,,Towing Services || Sandy Downs Racing,3/10/2012,5/1/2013,Active,Diamond,ID->Travel->Towing Services,ID->Travel->Sandy Downs Racing->Towing Services,,,,\n";
	echo ",,,,,,,,,,,,,,,,,House of Hair,,,135 N Higbee Ave,,United States,USA,,,Idaho,ID,Idaho Falls,,,,83401,(208) 220-1044,,,,Salons || Sandy Downs Racing,3/10/2012,5/1/2013,Active,Diamond,ID->Travel->Salons,ID->Travel->Sandy Downs Racing->Salons,,,,\n";
	echo ",,,,,,,,,,,,,,,,,Access Personal Training Studio,,http://www.kathyfit.com,475 Yellowstone Ave Ste I,,United States,USA,,,Idaho,ID,Pocatello,,,,83201,(208) 221-0364,,,,Gyms || Pocatello Downs,3/10/2012,5/1/2013,Active,Diamond,ID->Travel->Gyms,ID->Travel->Pocatello Downs->Gyms,,,,\n";
?>
